name: Lab CI

on:
    push:
        branches: [exp/creamery-lab]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
            - name: Install JS deps
              run: npm ci
            - name: Build lab client
              run: npm run build --if-present
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install Python deps
              run: |
                  python -m pip install -r analysis/requirements.txt
            - name: Run Python tests
              run: python -m pytest analysis/tests/test_pipeline.py -q
            - name: Validate lab routes
              run: node server-node/lab/validate_routes.mjs
